version: "3.9"
name: telegram-fitness-bot

services:
  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    environment:
      ENV: dev
      DEBUG: "1"
    command: ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers"]
    ports:
      - "8000:8000"
    restart: unless-stopped

  bot:
    build:
      context: ..
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    command: ["python", "-m", "app.telegram.bot"]
    restart: unless-stopped